### ISSUE TITLE
Add an option to specify a custom error handler

### ISSUE THREAD

**Issue by GoshaFighten** [DevExpress/DevExtreme.AspNet.Data#151]
There may be scenarios where it's necessary to process request failures in a custom way. For example, send an additional request with other parameters to fetch data, but without rejection of the main Deferred object returned in the `send` method. This is, for example, how this may be implemented: https://github.com/statler/DevExtreme.AspNet.Data/blob/master/js/dx.aspnet.data.js#L65. See the [https://www.devexpress.com/Support/Center/Question/Details/T553788](https://www.devexpress.com/Support/Center/Question/Details/T553788) ticket that provides a detailed description of this scenario.

**Comment by statler** [comment]
I am interested in this - can you please refer to my fork for an example of the kind of error handling that I would want to implement using this?
https://github.com/statler/DevExtreme.AspNet.Data

Thanks

**Comment by AlekseyMartynov** [comment]
With jQuery, the scenario described in https://devexpress.com/issue=T553788 can be implemented, without modifying the script, via `$.ajaxPrefilter`:

```js
$.ajaxPrefilter(function (_, ajaxSettings, xhr) {
    var d = $.Deferred();

    xhr
        .done(d.resolve)
        .fail(function (xhr, textStatus) {
            if (xhr.status === 401 && xhr.responseJSON && "newToken" in xhr.responseJSON) {
                console.log("Retry");
                // handle new token, etc
                $.ajax(ajaxSettings).then(d.resolve, d.reject);
            } else {
                d.reject(xhr, textStatus);
            }
        });

    return d.promise(xhr);
});
```

(based on https://stackoverflow.com/a/12446363)

I experimented with a possible callback for customizing AJAX requests (see https://github.com/AlekseyMartynov/DevExtreme.AspNet.Data/commit/a2bd38257d0d2d06e66615836e289a9f8fc2a984#diff-77af11b8eb0f57f8871e07189b2fee5fR680), but such an API didn't seem too useful in general.

I'm closing the ticket since there are easy workarounds.
