### ISSUE TITLE
"Maximum call stack size exceeded" due to faulty package-lock.json (jQuery-free NPM)

### ISSUE THREAD

**Issue by jtsom** [DevExpress/DevExtreme.AspNet.Data#214]
Similar issues that were supposed to have been fixed in the 1.4 version from https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/186 are still occuring. The console output is:

```
core.js:1448 ERROR RangeError: Maximum call stack size exceeded
    at new exports.Deferred (deferred.js:158)
    at inheritor._loadImpl (custom_store.js:221)
    at inheritor.eval [as _loadImpl] (class.js:16)
    at inheritor.load [as _loadFunc] (abstract_store.js:55)
    at invokeUserLoad (custom_store.js:71)
    at inheritor._loadImpl (custom_store.js:225)
    at inheritor.eval [as _loadImpl] (class.js:16)
    at inheritor.load [as _loadFunc] (abstract_store.js:55)
    at invokeUserLoad (custom_store.js:71)
    at inheritor._loadImpl (custom_store.js:225)
```

Packages:
```
    "devextreme": "17.2.6",
    "devextreme-angular": "^17.2.6",
    "devextreme-aspnet-data-nojquery": "1.4.0",
```

Simple setup to reproduce are included in issue 186 above. Seems to be an infinite recursion happening between:

``` load: function(options) {
        var that = this;
        options = options || {};
        this.fireEvent("loading", [options]);
        return this._withLock(this._loadImpl(options)).done(function(result) {
            that.fireEvent("loaded", [result, options])
        })
    }
```

and
```
_loadImpl: function(options) {
        var d = new Deferred;
        if ("raw" === this._loadMode) {
            runRawLoadWithQuery(d, this, options, false)
        } else {
            invokeUserLoad(this, options).done(function(data, extra) {
                d.resolve(data, extra)
            }).fail(createUserFuncFailureHandler(d));
            d = this._addFailHandlers(d)
        }
        return d.promise()
    }
```

![image](https://user-images.githubusercontent.com/13488/37100215-6001219a-21f0-11e8-82a3-673d6fd0526b.png)

**Comment by AlekseyMartynov** [comment]
We cannot reproduce this issue and have not received similar reports from other users.
Please provide us with an example app which we can launch and debug on our side (e.g. attach as ZIP).

**Comment by jtsom** [comment]
[plan-portal.zip](https://github.com/DevExpress/DevExtreme.AspNet.Data/files/1789669/plan-portal.zip)

I have a .NET Core backend that supplies the data, but that code never gets called - it enters the loop before making the call.

**Comment by AlekseyMartynov** [comment]
I launched the attached project on Windows using the following commands:

```
npm i
node_modules\.bin\ng serve --preserve-symlinks
```

No "Maximum call stack size exceeded" error.
In the browser, I can see that the web request is issued:

---

![issue-214](https://user-images.githubusercontent.com/4426185/37214343-c45b7358-23c5-11e8-96cc-8584ac4308b5.png)

---

Versions:

```
npm -v
5.7.1

node -v
v8.9.3
```

Have you tried to [clear npm cache](https://docs.npmjs.com/troubleshooting/try-clearing-the-npm-cache) and delete node_modules?

**Comment by AlekseyMartynov** [comment]
@jtsom

We have recently received a report about the same issue and finally we've been able to reproduce it.

It appears that a certain sequence of `npm install` commands can produce a `package-lock.json` file in which DevExtreme is included twice (at the top level and in `node_modules\devextreme-aspnet-data-nojquery\node_modules\devextreme`). This duplication breaks runtime logic and causes infinite recursion.

The plan-portal.zip archive attached in https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/214#issuecomment-371175888 doesn't include `package-lock.json`. That's why I was unable to see this behavior on my side.

The following steps should fix your lock-file:
- Delete `node_modules`
- Delete `package-lock.json`
- Run `npm install`

This could be an NPM bug (https://github.com/npm/npm/issues/18351).
However, we have some ideas on how to mitigate it on our side.

I'm reopening the ticket and will update it when we have more info.

**Comment by AlekseyMartynov** [comment]
Starting with [1.4.1](https://github.com/DevExpress/DevExtreme.AspNet.Data/releases/tag/1.4.1), `devextreme` is listed as a peer dependency. This will prevent nested installs.

**Comment by davidsk** [comment]
I'm experiencing a similar issue but I don't think it's to do with nested installs.  It seems that when using AMD, with or without jQuery, the datasource falls into a loop when fetching the data.

Samples attached

[web.zip](https://github.com/DevExpress/DevExtreme.AspNet.Data/files/2034276/web.zip)

Once downloaded:

- npm install
- npm run copy
- live-sever

Neither the AMD options work.  jQuery without AMD seems to work okay.

**Comment by AlekseyMartynov** [comment]
@davidsk 
In your AMD samples, DevExtreme is loaded twice. I can see entries for DevExtreme bundle (dx.all.js) and for DevExtreme modules (abstract_store.js):
 
![untitled-1](https://user-images.githubusercontent.com/4426185/40479661-de4fb83a-5f54-11e8-9222-561979192199.png)

Multiple instances of DevExtreme code don't recognize each other and, as a special case, [Class inheritance](https://github.com/DevExpress/DevExtreme/blob/80f9ffa089e95cb3e4d253d2b3c5af3316b75e92/js/core/class.js#L6-L16), breaks.

With AMD, don't load DevExtreme bundle, instead require individual widgets, as shown [here](https://github.com/DevExpress/devextreme-examples/blob/7b03de0d19ec04a5797000cb69b26e30e08c6bf3/requirejs-jquery/index.html#L25).  Without AMD, `devextreme-aspnet-data-nojquery` doesn't work due to the lack of exported internals.

cc @kvet @ovchinnikov
