### ISSUE TITLE
DataSourceLoader.Load server side queries not working when using a dynamic type DbSet

### ISSUE THREAD

**Issue by MrSantaCloud** [DevExpress/DevExtreme.AspNet.Data#304]
I am reporting a...
**feature request** but in the meanwhile it could be also intended as a bug report.

Description:
I'm also adding the source code that I will mention and discuss in this issue below.

I'm using Entity Framework Core and Reflections to dynamically obtain the DbSet of a db table by receiving its name as a parameter on a controller method.
All of these DBSets implements an interface named "ITbBasic" which grants that the properties named "Guid", "Name" and "Value" always exists on these tables.
This method also receives the DataSourceLoadOptionsBase with all the filters of the table/lookup who calls the method.
The issue comes out when I try to apply these filters on the IQueryable<ITbBasic> by using the DataSourceLoader.Load function.
For some reasons, it seems that the function fails on applying the filters and as a result it sends back to the client every single row, that is then filtered by client side as fallback option.

Here's the code, I'll be available for every  clarification

       
        [HttpPost("Test")]
        public IActionResult Test(DataSourceLoadOptions lo)
        {
            var queryParams = Request.Query.ToDictionary(x => x.Key, x => x.Value);

            if (String.IsNullOrWhiteSpace(queryParams["t"].ToString()))
            {
                return BadRequest("No Context received for Dropdown Data Request");
            }

            string tableName = queryParams["t"].ToString();

            Assembly[] assemblies = AppDomain.CurrentDomain.GetAssemblies();
            Type type  = (from xelement in (from app in assemblies
                                            select (from tip in app.GetTypes()
                                                    where tip.Name == name.Trim()
                                                    select tip).FirstOrDefault())
                          where xelement != null
                          select xelement).FirstOrDefault();

            if (type != null)
            {
              //This Set is an extension of the standard Set. See below
                var myContext = _context.Set(type) as IQueryable<ITbBasic>;

                if (myContext == null)
                {
                    return BadRequest("myContext is null");
                }

                var myContext2 = MyContext.Select(o=>new {
                    o.name,
                    o.value
                    o.gid
                });
                
                lo.Take = 100;

                return Ok( DataSourceLoader.Load(myContext, lo));
        }

         public static IQueryable<object> Set(this DbContext _context, Type t)
        {

            var res= _context.GetType().GetMethod("Set").MakeGenericMethod(t).Invoke(_context, null);

            return (IQueryable<object>)res;
        }

**Comment by AlekseyMartynov** [comment]
Internally, `DataSourceLoader` builds typed LINQ expressions based on the type `T` specified by the input `IQueryable<T>`.

For `IQueryable<ITbBasic>`, it's only possible to query against the members of `ITbBasic`.
In some cases, even interface members aren't visible due to the reasons described in:
- https://stackoverflow.com/q/1783379
- https://haacked.com/archive/2009/11/10/interface-inheritance-esoterica.aspx/

---

To query without knowing concrete types, you can force [dynamic evaluation](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/f3397a55a4f5b7aa0df00dc525cefbd4f033c903/net/DevExtreme.AspNet.Data/DynamicBindingHelper.cs#L16-L18) by converting `DbSet`'s to `Object` arrays:

```c#
_context.Set(type).Cast<object>().ToArray()
```

However, the drawbacks are significant:
- Queries are not translated to SQL
- [Dynamic Language Runtime](https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/dynamic-language-runtime-overview) is slow

---

If all types are known in advance then I suggest that you rather use a `switch` block to map table names to typed queries:

```c#
switch(t) {
    case "Type1": return DataSourceLoader.Load(_context.Set<Type1>(), lo);
    case "Type2": return DataSourceLoader.Load(_context.Set<Type2>(), lo);

    default:
        throw new NotSupportedException();
}
```

Generally, there's no magic grail that would allow to combine the performance of typed queries with the flexibility of dynamic binding.
