### ISSUE TITLE
How to use AutoMapper for LoadResult

### ISSUE THREAD

**Issue by itprodavets** [DevExpress/DevExtreme.AspNet.Data#335]
I have code:
```
            var list = _unitOfWork.DbContext.Models
                .FromSql(Resource.Models)
                .AsNoTracking();

            var result = DataSourceLoader.Load(list, request);
```
How I can change model after getting result?

**Comment by AlekseyMartynov** [comment]
Typically, model transformations are done prior to `Load`, because you want load options (sort, filter, etc) to match the model properties:

```c#
var projection = list.Select(i => ...);
var result = DataSourceLoader.Load(projection, request);
```

However, if you have a specific need to transform data after `DataSourceLoader.Load` then you can manipulate the `result.data` property.

https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/3eb32ba21a1e44626509508d7fd4e1d3e59c89d3/net/DevExtreme.AspNet.Data/ResponseModel/LoadResult.cs#L18

It's an opaque non-generic `IEnumerable` the exact item type of which depends on load options. It can be a collection of [groups](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/2.1.2/net/DevExtreme.AspNet.Data/ResponseModel/Group.cs), expando objects, or original data items.
