### ISSUE TITLE
.NET type DevExtreme.AspNet.Data.Types.AnonType cannot be mapped to a BsonValue.

### ISSUE THREAD

**Issue by alejackiu** [DevExpress/DevExtreme.AspNet.Data#430]
Hi,
I'm trying to use total summary in DataGrid using mongodb and it's throwing this error ".NET type DevExtreme.AspNet.Data.Types.AnonType cannot be mapped to a BsonValue.". I didnt find how to overcome this error.

**Comment by AlekseyMartynov** [comment]
Hello

Currently, there are known limitations for `IQueryable<BsonDocument>` sources. Please refer to issues #421 and #422 for more information.

In general, these 2 settings may help resolve `AnonType` errors:

```c#
loadOptions.RemoteGrouping = false;
loadOptions.RemoteSelect = false;
```

For better compatibility, I suggest that you use [mapped classes](http://mongodb.github.io/mongo-csharp-driver/2.5/reference/bson/mapping/) instead of `BSON` documents.

**Comment by AlekseyMartynov** [comment]
Reproduced.

Internal notes:
- Use `AllowEmpty = false` for Mongo at
   https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/4cfd796b39d861798d22ab102c9b49c4edcbf8aa/net/DevExtreme.AspNet.Data/DataSourceLoadContext.cs#L47
- `GroupSummary` without `Group` and without `TotalSummary` should not perform any aggregation.
- Notify `T900956` when fixed

**Comment by AlekseyMartynov** [comment]
Workaround:

```c#
BsonTypeMapper.RegisterCustomTypeMapper(
    Type.GetType("DevExtreme.AspNet.Data.Types.AnonType, DevExtreme.AspNet.Data"),
    new DevExtremeAspNetDataAnonTypeMapper()
);
```

```c#
class DevExtremeAspNetDataAnonTypeMapper : ICustomBsonTypeMapper {
    public bool TryMapToBsonValue(object value, out BsonValue bsonValue) {
        bsonValue = new BsonDocument();
        return true;
    }
}
```

**Comment by alejackiu** [comment]
Thanks, that works.
