### ISSUE TITLE
Paging is broken when dxDataGrid is sorted by a column with non-unique values

### ISSUE THREAD

**Issue by NikitaKunashov** [DevExpress/DevExtreme.AspNet.Data#82]
Once the grid is sorted by a column that has duplicated values, paging works wrong
![test video](https://cloud.githubusercontent.com/assets/23194319/20631340/fea912e0-b346-11e6-9ca2-f8ad8bf36826.gif)
[T454358(new).zip](https://github.com/DevExpress/DevExtreme.AspNet.Data/files/613640/T454358.new.zip)

**Comment by jtheisen** [comment]
I [wrote up why this is in the ticket I filed on devexpress.com](https://www.devexpress.com/support/center/Question/Details/T454358) - I think that will be helpful.

**Comment by AlekseyMartynov** [comment]
Thanks @jtheisen for reporting this.
The worst thing is that there's no universal way to automatically deternime primary key properties, because the concept of primary keys doesn't belong to pure LINQ.

I think we need to add `DataSourceLoadOptions.PrimaryKey` property of type `String[]` and also try to populate keys automatically from data annotation attributes if they are available.

As it turns out, the `DefaultSort` prop doesn't work and probably needs to be deprecated.

We are working on a fix.

**Comment by AlekseyMartynov** [comment]
PR is ready: https://github.com/DevExpress/DevExtreme.AspNet.Data/pull/83

**Comment by liuyuanjie** [comment]
Per your description, I think you need to read the article which is talking about Using OFFSET and FETCH to limit the rows returned for better understanding. Please see:
[Using OFFSET and FETCH to limit the rows returned](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql?view=sql-server-2017#using-offset-and-fetch-to-limit-the-rows-returned)
